name: litenet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy  # for testing and benchmarking
  - pytest  # keeping this as testing is important
  - cmake>=3.15
  # - gcc  # use clang instead